using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace FBone.Migrations
{
    /// <inheritdoc />
    public partial class AddedEmailTemplatesForAudit : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("INSERT into EmailTemplate (emailid, subject, body) VALUES (N'AuditStarted', N'FB one. ACTION REQUIRED. Audit started', N'<p style=''color:red''><b>This is an automated message. Please do not reply to this email...</b></p><hr>Audit with #@number@ has been started <br>Please review required actions in the audit by accessing <a href=''@AuditURL@''>this link</a><hr><b>Note:</b> This email was generated by TCO FB one application, if you are not the right person or you have questions please contact <a href=''mailto:autois3@tengizchevroil.com''>support team</a>')");
            migrationBuilder.Sql("INSERT into EmailTemplate (emailid, subject, body) VALUES (N'AuditRejected', N'FB one. Audit rejected', N'<p style=''color:red''><b>This is an automated message. Please do not reply to this email...</b></p><hr>Audit with #@number@ has been rejected. Please review comments in the audit history by accessing <a href=''@AuditURL@''>this link</a><hr><b>Note:</b> This email was generated by TCO FB one application, if you are not the right person or you have questions please contact <a href=''mailto:autois3@tengizchevroil.com''>support team</a>')");
            migrationBuilder.Sql("INSERT into EmailTemplate (emailid, subject, body) VALUES (N'AuditVerificationStarted', N'FB one. ACTION REQUIRED. Audit verification', N'<p style=''color:red''><b>This is an automated message. Please do not reply to this email...</b></p><hr>Audit #@number@ verification is required<br>Please review comments in the audit by accessing <a href=''@AuditURL@''>this link</a><hr><b>Note:</b> This email was generated by TCO FB one application, if you are not the right person or you have questions please contact <a href=''mailto:autois3@tengizchevroil.com''>support team</a>')");
            migrationBuilder.Sql("INSERT into EmailTemplate (emailid, subject, body) VALUES (N'AuditApprovalStarted', N'FB one. ACTION REQUIRED. Audit approval', N'<p style=''color:red''><b>This is an automated message. Please do not reply to this email...</b></p><hr>Audit #@number@ approval is required<br>Please review comments in the audit by accessing <a href=''@AuditURL@''>this link</a><hr><b>Note:</b> This email was generated by TCO FB one application, if you are not the right person or you have questions please contact <a href=''mailto:autois3@tengizchevroil.com''>support team</a>')");
            migrationBuilder.Sql("INSERT into EmailTemplate (emailid, subject, body) VALUES (N'AuditCompleted', N'FB one. Audit completed', N'<p style=''color:red''><b>This is an automated message. Please do not reply to this email...</b></p><hr>Audit #@number@ has been completed<br>Please review comments in the audit by accessing <a href=''@AuditURL@''>this link</a><hr><b>Note:</b> This email was generated by TCO FB one application, if you are not the right person or you have questions please contact <a href=''mailto:autois3@tengizchevroil.com''>support team</a>')");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {

        }
    }
}
